### ISSUE TITLE
Out of memory with explicit_antisym model

### ISSUE THREAD

**Issue by BaoHhhhhhan** [jeffminlin/vmcnet#96]
I want to use explicit_antisym model, the configuration is listed below:
      "--config.problem.ion_pos", "((0.0, 0.0, -2.0), (0.0, 0.0, 2.0))", 
      "--config.problem.ion_charges", "(7.0, 7.0)", 
      "--config.problem.nelec", "(7, 7)",      
      "--config.model.type", "explicit_antisym",
      "--config.model.explicit_antisym.antisym_type", "generic",
      "--config.logging_level", "INFO",
      "--config.vmc.nepochs", "10",
      "--config.eval.nepochs", "10"
The program will crash down for out of memory.
I found that the broadcast_x_shape in generic antisymmetric layer was too large to put broadcasted leaf_perms  in memory. Could you please give an example running this program with explicit_antisym model?

**Comment by jeffminlin** [comment]
Hi, you'll need to run the explicit antisym models on smaller problems, as the way they are implemented here is to parallelize as much as possible, which causes the memory requirements to grow factorially with the number of particles.
